name: Weekly PDF Scraper

on:
  schedule:
    - cron: '0 8 * * 1'  # 每周一 8:00 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-pdfs
          path: 'pdfs/*.pdf'
